# This Source Code Form is subject to the terms of the Mozilla Public
# # License, v. 2.0. If a copy of the MPL was not distributed with this
# # file, You can obtain one at http://mozilla.org/MPL/2.0/.

all:

install:
	install -d /usr/local/bin
	install -m 755 fastping.sh /usr/local/bin
	install -m 755 nmss.sh /usr/local/bin
	install -m 755 znmss.sh /usr/local/bin

clean:
